name: Deploy Application Infra
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/application.yml'
      - 'infra/tf/dockerfile'
      - 'infra/tf/application/**'
      - 'infra/docker-compose.yml'
      - 'infra/docker-compose.app.yml'
      - 'Makefile'
jobs:
  terraform_plan_application:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ENVFILE: ../env.template
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan ENV=app   

  terraform_apply_application:
    environment:
      name: approval
    needs: terraform_plan_application
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ENVFILE: ../env.template
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan ENV=app 
    - name: Terraform_Apply
      run: make run_apply ENV=app 




