name: Destroy Application Infra
on:
  push:
    branches:
      - destroy
    paths:
      - '.github/workflows/application.yml'
      - 'infra/tf/dockerfile'
      - 'infra/tf/application/**'
      - 'infra/docker-compose.yml'
      - 'infra/docker-compose.app.yml'
      - 'Makefile'
jobs:
  terraform_destroy_plan_application:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan ENV=app    

  terraform_destroy_apply_application
    environment:
      name: approval
    needs: terraform_destroy_plan_application
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply ENV=app 
