name: Destroy Network Infra
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
  push:
    branches:
      - destroy
    paths:
      - '.github/workflows/network.yml'
      - 'infra/tf/dockerfile'
      - 'infra/tf/network/**'
      - 'infra/docker-compose.yml'
      - 'infra/docker-compose.vpc.yml'
      - 'Makefile'
jobs:
  terraform_destroy_plan_network:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ENVFILE: ../env.template
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Terraform_Destroy_Plan
        run: make run_destroy_plan ENV=vpc    

  terraform_destroy_apply_network:
    environment:
      name: approval
    needs: terraform_destroy_plan_network
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ENVFILE: ../env.template
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Terraform_Destroy_Apply
        run: make run_destroy_apply ENV=vpc 
